### ISSUE TITLE
dev branch installation bug

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/rltk#38]
Installing the rltk dev branch requires many of the packages specified in the `requirements.txt` file to be already installed.

This is because setup.py gets `__version__` from rltk package:

https://github.com/usc-isi-i2/rltk/blob/dev/setup.py#L3

And, the rltk package imports other rltk modules:

https://github.com/usc-isi-i2/rltk/blob/dev/rltk/__init__.py#L3

**Comment by GreatYYX** [comment]
Thanks @kyao , sorry for the delay, I just noticed this issue. You are right, this requires some packages to be installed first.
For single sourcing package version (https://packaging.python.org/guides/single-sourcing-package-version/), rltk was using a VERSION text file. It got updated to be a `__version__` variable in root level `__init__.py` file from one recent release. This is more convenient for cross-reference in scripts.
I guess the fix could be that let setup.py read `rltk.__init__` as a text file instead of a python package.
